# For non-draft changes to named release branches:
# - Check if the user is a maintainer (listed below in the MERGERS env var).
# - If so, approve the pull request.
#   - Merge the PR when the author comments `@openedx-community-bot merge`.
#
# Required organization secrets
# - CC_GITHUB_TOKEN or GITHUB_TOKEN

name: Automerge BTR open-release PRs

env:
  # The GitHub user names of people allowed to tell the bot to merge.
  # From the "All release branches" entries on the wiki:
  # https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Current+Core+Contributors
  MERGERS: arbrandes BbrSofiane cmltaWt0 regisb

on:
  # This action is meant to be used from other actions.
  # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
  - workflow_call

defaults:
  run:
    shell: bash

jobs:
  automerge:
    if: ${{ (github.event.issue.pull_request && !github.event.issue.pull_request.draft) || (github.event.pull_request && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check merge rights
        id: check
        # This workflow used to use tspascoal/get-user-teams-membership,
        # but it stopped working, and this works.
        run: |
          set -x
          if echo $MERGERS | grep -q -w ${{ github.actor }}; then
            permok=true
          else
            permok=false
          fi
          echo "PERMOK=$permok" >> $GITHUB_ENV

      - name: Approve PR
        if: ${{ env.PERMOK == 'true' && (github.event.action == 'opened' || github.event.action == 'ready_for_review') }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.CC_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          event: APPROVE
          body: |
            :+1:

            When you're ready to merge, add a comment that says
            > @openedx-community-bot merge

            and we'll handle the rest!

      - name: Label PR as auto-mergeable
        if: ${{ env.PERMOK == 'true' && contains(github.event.comment.body, '@openedx-community-bot merge') }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: 'automerge'
          repo-token: ${{ secrets.CC_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Automerge
        if: ${{ env.PERMOK == 'true' }}
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.CC_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: |
            merge(#{pullRequest.number}): {pullRequest.title}

            {pullRequest.body}
